### ISSUE TITLE
Use Redis Keyspace events for eviction

### ISSUE THREAD

**Issue by ymotton** [null-d3v/L1L2RedisCache#3]
When considering this solution we ran into some questions:
- What happens when a consumer of this library removes a key, but kills the thread before publishing the eviction message? 
- What happens when a key is evicted from the redis store directly, without running through this tooling?
- What happens when a key expires in the store?
- What happens if we miss an eviction message?

In each case your consumers will have stale data in their in-memory copy.

We concluded that a better approach would be using the redis keyspace notificiations ( https://redis.io/topics/notifications ). Keyspace notifications are published by redis as a result of manipulating its internal state. This seems to solve the first 3 issues.

The 4th issue is tricky. As long as redis doesn't implement reliable messaging we run the risk of missing eviction messages. Their future plans do seem to include this, however.

Interested to hear your thoughts. Thanks!

**Comment by null-d3v** [comment]
I appreciate the interest and questions!

> What happens when a consumer of this library removes a key, but kills the thread before publishing the eviction message?

There is a key-based locking mechanism which enforces atomicity, preventing simultaneous changes to the same key from rolling over each other and leaving the memory cache in a damaged state. Picture a `Set()` occurring just prior to a `Remove()`. Without key atomicity and with unfortunate timing, the `Set()` could populate the memory entry after the `Remove()`, dissociating the memory cache.

This is relevant as it somewhat prohibits asynchronous cooperative cancellation; even asynchronous calls use a lock statement block which cannot execute anything asynchronously. So in the event of a cancellation request, all calls, asynchronous included, will execute in entirety.

Threads being unsafely killed could produce unsafe results in specific circumstances. Entries are changed in the order of Redis, memory, and then messages are published. If the thread was unsafely aborted in the ticks between Redis being updated and the message published, there is the possibility that the Redis entry is altered without a corresponding pub/sub message. This would leave other clients with 'dated' memory cache correlate until the memory entries are evicted. This is a unfortunate but rare possibility that could be mitigated in a few ways, such as lower TTLs or maybe introducing a feature of somehow specifying TTLs for memory cache entries. This could be by way of a raw value or even a simple proportion. Thinking about it now, this is definitely something I'll plan on exploring for a future release.

> What happens when a key is evicted from the redis store directly, without running through this tooling?

Similar to the above, any clients with a memory entry for that key would be dissociated from the Redis entry. This would be in place until the clients evicted the memory entry by way of TTL, programmatically, or by flushing the memory cache completely.

> What happens when a key expires in the store?

All memory cache entries will match their correlate Redis entry's expiration. So when a Redis key expires, so will any clients' memory entries for that key.

> What happens if we miss an eviction message?

The general premise is that any client capable of caching entries within Redis and memory should be capable of processing pub/sub messages to evict memory entries. Being unable to do the latter should prohibit the former. Clients in the act of startup/shutdown may miss a message while the subscriber is configured. However they should not necessarily care about these messages as they either have no memory entries to evict or the memory entries are quickly becoming irrelevant.

However the unreliability of pub/sub does pose a problem an intermittent connection problem possibly dropping a message. Though this would be a problem though any any kind of cache synchronization approach that utilizes pub/sub.


Keyspace notifications are absolutely a great alternative! In my personal experience though they were somewhat undesirable as they are unilaterally on or off per command subject. My use of `L1L2RedisCache` was only a small subset cluster traffic and I did not favor incurring the global performance penalty for my own specific use. If I had complete jurisdiction of the cluster, or my own for my specific case I probably would have used them. In fact, this very library may have been set up for only keyspace notifications instead of generating its own.

**Comment by null-d3v** [comment]
Relevant to the last point, I have published a pre-release package that has options for keyspace and keyevent notifications. Standard use is explained in the [updated readme](https://github.com/null-d3v/L1L2RedisCache#messagingtype). I wouldn't personally turn on either notification type on the Redis server specifically for use of this library. However if these settings were already enabled on the server, using the appropriate option would allow any subscribed memory caches to evict entries based on raw Redis operations.
